routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "ProductController@index");
Route::resource("/products","ProductController");

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
       protected $fillable=[
        "name",
        "description",
        "quantity",
        "status",
        "price",
        "sku"
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products=Product::all();
        return view('products.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product= new Product();
        return view('products.create',compact('product'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules=[
            'name'=>'required',
            'quantity'=>'required|integer|min:0',
            'price'=>'required|integer|min:1'

        ];
        $this->validate($request,$rules);
        $data=$request->all();
        $data['status']=$request->status;
        //return  $data['status'];
        $product=Product::create($data);

        return view('products.show',compact('product'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $rules=[
            'name'=>'required',
            'quantity'=>'required|integer|min:0',
            'price'=>'required|integer|min:1'

        ];
        $this->validate($request,$rules);
        $product->name=$request->name;
        $product->description=$request->description;
        $product->quantity=$request->quantity;
        $product->status=$request->status;
        $product->price=$request->price;
        $product->sku=$request->sku;
        $product->save();

        return view('products.show',compact('product'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        $products=Product::all();
        return view('products.index',compact('products'));

    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container ">
			<h1>Add Product</h1>
			<form action="{{route('products.store')}}" method="POST">
			@csrf

			<div class="form-group row">
				<label class="col-sm-2 control-label">
					Name : 
				</label>
			    <div class="col-sm-9">
			    	<input type="text" name="name" class="form-control {{$errors->has('name')?'is-invalid':''}}" autocomplete="off" value="{{old('name')}}">
			    </div>
			</div>
			@if($errors->has('name'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('name')}}</strong>
			    </div>
		    @endif

			<div class="form-group row">
				<label class="col-sm-2 control-label">
					Description : 
				</label>
			    <div class="col-sm-9">
			    	<textarea rows="10" name="description" class="form-control {{$errors->has('description')?'is-invalid':''}}" autocomplete="off" value="{{old('description')}}">{{old('description')}}</textarea>
			    </div>
			</div>
			@if($errors->has('description'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('description')}}</strong>
			    </div>
		    @endif
	

			<div class="form-group row">
				<label class="col-sm-2 control-label">
					Quantity	 : 
				</label>
			    <div class="col-sm-9">
			    	<input type="text" name="quantity" class="form-control {{$errors->has('quantity')?'is-invalid':''}}" autocomplete="off">
			    </div>
			</div>
			@if($errors->has('quantity'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('quantity')}}</strong>
			    </div>
		    @endif

		    <div class="form-group row">
		      <label class="col-sm-2  form-check-label">
		           Status :
		       </label>
		      <div class="col-sm-6">    
		         <select class="form-control form-block" name="status">
		          <option value="0">Select Status</option>
		          <option value="good">Good</option>
		          <option value="used">Used</option>
		          <option value="old">Old</option>
		         </select> 
		        </div>
		       </div>

			 <div class="form-group row">
			    <label class="col-sm-2  form-check-label">Sku :</label>
			     <div class="col-sm-9">
			    	<input type="text" name="sku" class="form-control {{$errors->has('sku')?'is-invalid':''}}" autocomplete="off">
			    </div>
			  </div>

			  @if($errors->has('sku'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('sku')}}</strong>
			    </div>
			   @endif

			  	<div class="form-group row">
					<label class="col-sm-2 control-label">
						Price : 
					</label>
				    <div class="col-sm-9">
				    	<input type="text" name="price" class="form-control {{$errors->has('price')?'is-invalid':''}}" autocomplete="off">
				    </div>
				</div>
				@if($errors->has('price'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('price')}}</strong>
			    </div>
			   @endif

				  <div class="form-group row ">
				    	<button type="submit" name="save" class="btn btn-info">Add Product</button>
				</div>
			</form>
            <hr>
			|<a href="/products"> Back to Products</a> |
		</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container ">
			<h1>Add Product</h1>
			<form action="{{route('products.update',$product->id)}}" method="POST">
			@csrf
			@method('PUT')
			<div class="form-group row">
				<label class="col-sm-2 control-label">
					Name : 
				</label>
			    <div class="col-sm-9">
			    	<input type="text" name="name" class="form-control {{$errors->has('name')?'is-invalid':''}}" autocomplete="off" value="{{old('name',$product->name)}}">
			    </div>
			</div>
			@if($errors->has('name'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('name')}}</strong>
			    </div>
		    @endif

			<div class="form-group row">
				<label class="col-sm-2 control-label">
					Description : 
				</label>
			    <div class="col-sm-9">
			    	<textarea rows="10" name="description" class="form-control {{$errors->has('description')?'is-invalid':''}}" autocomplete="off" value="{{old('description')}}">{{old('description',$product->description)}}</textarea>
			    </div>
			</div>
			@if($errors->has('description'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('description')}}</strong>
			    </div>
		    @endif
	

			<div class="form-group row">
				<label class="col-sm-2 control-label">
					Quantity	 : 
				</label>
			    <div class="col-sm-9">
			    	<input type="text" name="quantity" class="form-control {{$errors->has('quantity')?'is-invalid':''}}" value="{{old('quantity',$product->quantity)}}" autocomplete="off">
			    </div>
			</div>
			@if($errors->has('quantity'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('quantity')}}</strong>
			    </div>
		    @endif

		    <div class="form-group row">
		      <label class="col-sm-2  form-check-label">
		           Status :
		       </label>
		      <div class="col-sm-6">    
		      	@php
		      	 $stat=$product->status;
		      	@endphp
		         <select class="form-control form-block" name="status">
		          <option value="0">Select Status</option>
		          @if($stat=="good")
			          <option value="good" Selected>Good</option>
			          <option value="used">Used</option>
			          <option value="old">Old</option>
		          @elseif($stat=="used")
			          <option value="good" >Good</option>
			          <option value="used" Selected>Used</option>
			          <option value="old">Old</option>
		          @elseif($stat=="old")
		              <option value="good" >Good</option>
			          <option value="used" >Used</option>
			          <option value="old" Selected>Old</option>
		          @endif
		         </select> 
		        </div>
		       </div>
               <div class="form-group row">
			    <label class="col-sm-2  form-check-label">Sku :</label>
			     <div class="col-sm-9">
			    	<input type="text" name="sku" class="form-control {{$errors->has('sku')?'is-invalid':''}}" value="{{old('sku',$product->sku)}}" autocomplete="off">
			    </div>
			  </div>
			  @if($errors->has('sku'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('sku')}}</strong>
			    </div>
			   @endif

			  	<div class="form-group row">
					<label class="col-sm-2 control-label">
						Price : 
					</label>
				    <div class="col-sm-9">
				    	<input type="text" name="price" class="form-control {{$errors->has('price')?'is-invalid':''}}" value="{{old('price',$product->price)}}"  autocomplete="off">
				    </div>
				</div>
				@if($errors->has('price'))
			    <div class="invalid-feedback">
			        <strong>{{$errors->first('price')}}</strong>
			    </div>
			   @endif

				  <div class="form-group row ">
				    	<button type="submit" name="save" class="btn btn-info">Edit Product</button>
				</div>
			</form>
            <hr>
			|<a href="/products"> Back to Products</a> |
		</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
     <div >
          <a href="{{route('products.create')}}" class="btn btn-outline-primary btn-sm float-right">Add Product</a>
     </div>
     <br>
     <br>
	<table class="table">
		<thead> 
			<th>ID</th>
			<th>Name</th>
			<th>Description</th>
			<th>Quantity</th>
			<th>Sku</th>
			<th>Status</th>
			<th>Price</th>
			<th>Options</th>
		</thead>
		@if(empty($products))
		<tr>
			<td colspan="8">Sorry No Products </td>
		</tr>
		@else
          @foreach($products as $product)
          <tr>
          	<td>
          	   {{$product->id}}
          	</td>
          	<td>
          	  <a href="{{route('products.show',$product->id)}}">{{$product->name}}</a> 
          	</td>
          	<td>
          	   {{$product->description}}
          	</td>
          	<td>
          	   {{$product->quantity}}
          	</td>
          	<td>
          	   {{$product->sku}}
          	</td>
          	<td>
          	   {{$product->status}}
          	</td>
          	<td>
          	   {{$product->price}}
          	</td>
          	<td>
          		<a href="{{route('products.edit',$product->id)}}" class="btn btn-outline-info btn-sm">Edit</a>
          		<form method="POST" action="{{route('products.destroy',$product->id)}}" class="delProduct">
          			@csrf
          			@method('DELETE')
          			<input type="submit" name="Delete" value="Delete" class="btn btn-outline-danger btn-sm">
          		</form>
          	</td>
          </tr>
          @endforeach
		@endif
	</table>
</div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card">
	<div class="card-body">
		<h3>{{$product->name}}</h3>
		<table class="table text-center">
			<tr>
				<td>
					{{$product->id}}
				</td>
			</tr>
			<tr>
				<td>
					{{$product->description}}
				</td>
			</tr>
			<tr>
				<td>
					{{$product->quantity}}
				</td>
			</tr>
			<tr>
				<td>
					{{$product->sku}}
				</td>
			</tr>
			<tr>
				<td>
					{{$product->status}}
				</td>
			</tr>
			<tr>
				<td>
					{{$product->price}}
				</td>
			</tr>
			<tr>
				<td>
					<a href="{{route('products.edit',$product->id)}}" class="btn btn-outline-info btn-sm">Edit</a>
	          		<form method="POST" action="{{route('products.destroy',$product->id)}}" class="delProduct">
	          			@csrf
	          			@method('DELETE')
	          			<input type="submit" name="Delete" value="Delete" class="btn btn-outline-danger btn-sm">
	          		</form>
				</td>
			</tr>
		</table>
	</div>
</div>
@endsection